management:
 endpoints:
    web:
     exposure:
        include: health, info, beans, *
 endpoint:
    metrics:
        enabled: true
    health:
      show-details: always
    beans:
        enabled: true
 security:
    enabled: false



